#!/bin/sh
# Zemtik installer — POSIX shell, no sudo required.
# Usage: sh install.sh [--binary-dir <dir>]
# Installs the zemtik binary to ~/.local/bin (or the provided dir),
# creates ~/.zemtik structure, and adds the binary dir to PATH in the
# relevant shell rc file.

set -e

BINARY_DIR="${BINARY_DIR:-$HOME/.local/bin}"
ZEMTIK_HOME="$HOME/.zemtik"

# Allow override via argument
while [ "$#" -gt 0 ]; do
    case "$1" in
        --binary-dir) BINARY_DIR="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

echo "╔══════════════════════════════════════════════════╗"
echo "║   Zemtik Installer                               ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# Detect platform
OS="$(uname -s)"
ARCH="$(uname -m)"
echo "[INSTALL] Platform: $OS / $ARCH"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Create ~/.zemtik directory structure
echo "[INSTALL] Creating ~/.zemtik directory structure..."
mkdir -p "$ZEMTIK_HOME/circuit"
mkdir -p "$ZEMTIK_HOME/runs"
mkdir -p "$ZEMTIK_HOME/keys"
mkdir -p "$ZEMTIK_HOME/receipts"
mkdir -p "$ZEMTIK_HOME/.tmp"

# Copy circuit source and vendor dependency (required for nargo)
if [ -d "$SCRIPT_DIR/circuit" ]; then
    echo "[INSTALL] Copying circuit files to $ZEMTIK_HOME/circuit/..."
    cp -r "$SCRIPT_DIR/circuit/." "$ZEMTIK_HOME/circuit/"
    # Remove any stale top-level Nargo.toml left by pre-v0.8 installs.
    # The mini-circuit layout (sum/, count/, lib/) must NOT have a parent
    # Nargo.toml — nargo would walk up to it and compile the wrong package.
    rm -f "$ZEMTIK_HOME/circuit/Nargo.toml"
fi
if [ -d "$SCRIPT_DIR/vendor" ]; then
    echo "[INSTALL] Copying vendor dependencies to $ZEMTIK_HOME/vendor/..."
    mkdir -p "$ZEMTIK_HOME/vendor"
    cp -r "$SCRIPT_DIR/vendor/." "$ZEMTIK_HOME/vendor/"
fi

# Install binary
echo "[INSTALL] Installing zemtik binary to $BINARY_DIR..."
mkdir -p "$BINARY_DIR"

if [ -f "$SCRIPT_DIR/target/release/zemtik" ]; then
    cp "$SCRIPT_DIR/target/release/zemtik" "$BINARY_DIR/zemtik"
    chmod +x "$BINARY_DIR/zemtik"
    echo "[INSTALL] Copied release binary to $BINARY_DIR/zemtik"
elif [ -f "$SCRIPT_DIR/zemtik" ]; then
    cp "$SCRIPT_DIR/zemtik" "$BINARY_DIR/zemtik"
    chmod +x "$BINARY_DIR/zemtik"
    echo "[INSTALL] Copied pre-built binary to $BINARY_DIR/zemtik"
else
    echo "[INSTALL] No binary found at target/release/zemtik or alongside install.sh"
    echo "[INSTALL] Build with: cargo build --release"
    echo "[INSTALL] Then re-run this installer."
    exit 1
fi

# Generate default config if not present
CONFIG_FILE="$ZEMTIK_HOME/config.yaml"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "[INSTALL] Creating default config at $CONFIG_FILE..."
    cp "$SCRIPT_DIR/config.example.yaml" "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
fi

# Copy schema_config.example.json → ~/.zemtik/schema_config.json if not present
SCHEMA_FILE="$ZEMTIK_HOME/schema_config.json"
if [ ! -f "$SCHEMA_FILE" ]; then
    if [ -f "$SCRIPT_DIR/schema_config.example.json" ]; then
        echo "[INSTALL] Creating default schema_config at $SCHEMA_FILE..."
        cp "$SCRIPT_DIR/schema_config.example.json" "$SCHEMA_FILE"
        chmod 600 "$SCHEMA_FILE"
    else
        echo "[INSTALL] Warning: schema_config.example.json not found — skipping schema_config setup"
        echo "[INSTALL] Create $SCHEMA_FILE manually before running in proxy mode."
    fi
fi

# Update PATH in the relevant shell rc file
update_path() {
    RC_FILE="$1"
    PATH_LINE="export PATH=\"\$PATH:$BINARY_DIR\""
    if [ -f "$RC_FILE" ] && grep -q "$BINARY_DIR" "$RC_FILE" 2>/dev/null; then
        echo "[INSTALL] PATH already configured in $RC_FILE"
        return
    fi
    echo "" >> "$RC_FILE"
    echo "# Added by Zemtik installer" >> "$RC_FILE"
    echo "$PATH_LINE" >> "$RC_FILE"
    echo "[INSTALL] Added $BINARY_DIR to PATH in $RC_FILE"
}

case "$SHELL" in
    */zsh)  update_path "$HOME/.zshrc" ;;
    */bash) update_path "$HOME/.bashrc" ;;
    */fish) echo "[INSTALL] Fish shell detected — add $BINARY_DIR to fish path manually" ;;
    *)      update_path "$HOME/.profile" ;;
esac

# Verify installation
export PATH="$PATH:$BINARY_DIR"
if zemtik --version 2>/dev/null; then
    echo ""
    echo "[INSTALL] Installation complete!"
else
    echo ""
    echo "[INSTALL] Binary installed. Restart your shell or run:"
    echo "  export PATH=\"\$PATH:$BINARY_DIR\""
fi

# MCP wrapper — creates ~/.zemtik/bin/zemtik-mcp for Claude Desktop integration.
# Claude Desktop requires an absolute path to an executable; this wrapper
# provides a stable entry point that calls the installed zemtik binary.
echo "[INSTALL] Setting up Claude Desktop MCP integration..."
mkdir -p "$ZEMTIK_HOME/bin"
MCP_WRAPPER="$ZEMTIK_HOME/bin/zemtik-mcp"
cat > "$MCP_WRAPPER" <<EOF
#!/bin/sh
# Zemtik MCP wrapper — called by Claude Desktop (STDIO subprocess).
# Generated by install.sh. Do not edit directly; re-run install.sh to regenerate.
exec "$BINARY_DIR/zemtik" mcp "\$@"
EOF
chmod +x "$MCP_WRAPPER"
echo "[INSTALL] MCP wrapper written to $MCP_WRAPPER"

# Print Claude Desktop config block
if [ "$OS" = "Darwin" ]; then
    CLAUDE_CONFIG="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
elif [ -n "$APPDATA" ]; then
    CLAUDE_CONFIG="$APPDATA\\Claude\\claude_desktop_config.json"
else
    CLAUDE_CONFIG="~/.config/Claude/claude_desktop_config.json"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   Claude Desktop MCP Setup                                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Add this to: $CLAUDE_CONFIG"
echo ""
echo '  "mcpServers": {'
echo '    "zemtik": {'
echo "      \"command\": \"$MCP_WRAPPER\","
echo '      "env": {'
echo '        "ZEMTIK_MCP_API_KEY": "<your-api-key>"'
echo '      }'
echo '    }'
echo '  }'
echo ""
echo "  Then restart Claude Desktop. Zemtik will attest every tool call."
echo "  View audit log: zemtik list-mcp"
echo "  Full docs: docs/MCP_ATTESTATION.md"
echo ""

echo ""
echo "  Next steps:"
echo "  1. Set OPENAI_API_KEY in your environment or ~/.zemtik/config.yaml"
echo "  2. Edit ~/.zemtik/schema_config.json to configure your table sensitivities"
echo "  3. Run: zemtik proxy   (for ZK proxy mode)"
echo "  4. Run: zemtik mcp     (for Claude Desktop MCP integration)"
echo "  5. Run: zemtik list    (to view ZK receipts)"
echo "  6. Run: zemtik list-mcp  (to view MCP audit records)"
echo ""
